spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:training_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:training_user}
    password: ${DB_PASSWORD:training_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/seed/local
    baseline-on-migrate: false
